### PR TITLE
Add coafile

### PR DESCRIPTION
**Pull request by coafile**

### CODE REVIEW

**Comment by hemangsk** [comment]
Comment on 82a52196492df46517c0fdecfe4e0b1da987e98c, file README.md, line 5.

The text does not comply to the set style.

*Origin: MarkdownBear, Section: `markdown`.*

The issue can be fixed by applying the following patch:

```diff
--- a/README.md
+++ b/README.md
@@ -3,6 +3,7 @@
 ### Usage
 
 Install node and npm for your OS.
+
 ```
 $ npm install
 $ node app.js
```

**Comment by hemangsk** [comment]
Comment on 82a52196492df46517c0fdecfe4e0b1da987e98c, file README.md, line 1.

The text does not comply to the set style.

*Origin: MarkdownBear, Section: `markdown`.*

The issue can be fixed by applying the following patch:

```diff
--- a/README.md
+++ b/README.md
@@ -1,4 +1,4 @@
-# Recruitment Portal 
+# Recruitment Portal
 
 ### Usage
 
```

**Comment by hemangsk** [comment]
Holy shit ❌

**Comment by hemangsk** [comment]
@surender7790 its doing too much linting, lets keep only the relevant linters

**Comment by surender7790** [comment]
@hemangsk  yepp.

**Comment by hemangsk** [comment]
Comment on e0817a5542d9378981fd6965bf8ce8a9d9d7250b, file public/stylesheets/partials/head.css, line 37.

Line contains following spacing inconsistencies:
- No newline at EOF.

*Origin: SpaceConsistencyBear, Section: `cli`.*

The issue can be fixed by applying the following patch:

```diff
--- a/public/stylesheets/partials/head.css
+++ b/public/stylesheets/partials/head.css
@@ -34,4 +34,4 @@
 nav {
     text-align: center;
     background-color: #1A237E !important;
-}+}
```

**Comment by hemangsk** [comment]
Comment on e0817a5542d9378981fd6965bf8ce8a9d9d7250b, file public/stylesheets/partials/footer.css, line 18.

Line contains following spacing inconsistencies:
- No newline at EOF.

*Origin: SpaceConsistencyBear, Section: `cli`.*

The issue can be fixed by applying the following patch:

```diff
--- a/public/stylesheets/partials/footer.css
+++ b/public/stylesheets/partials/footer.css
@@ -15,4 +15,4 @@
     font-size: 12px;
     text-transform: uppercase;
     letter-spacing: 0.1em;
-}+}
```

**Comment by hemangsk** [comment]
Comment on e0817a5542d9378981fd6965bf8ce8a9d9d7250b, file README.md, line 1.

Line contains following spacing inconsistencies:
- Trailing whitespaces.

*Origin: SpaceConsistencyBear, Section: `cli`.*

The issue can be fixed by applying the following patch:

```diff
--- a/README.md
+++ b/README.md
@@ -1,4 +1,4 @@
-# Recruitment Portal 
+# Recruitment Portal
 
 ### Usage
 
```

**Pull request merged**
